pub const describe_instances_test_response =
    \\<?xml version="1.0" encoding="UTF-8"?>
    \\<DescribeInstancesResponse xmlns="http://ec2.amazonaws.com/doc/2016-11-15/">
    \\    <requestId>37f07eb3-4a90-4166-b36f-225f79b6a0fe</requestId>
    \\    <reservationSet>
    \\        <item>
    \\            <reservationId>r-0aa8dc779a7a3a76a</reservationId>
    \\            <ownerId>550620852718</ownerId>
    \\            <groupSet/>
    \\            <instancesSet>
    \\                <item>
    \\                    <instanceId>i-07d9a800b9cf6cb02</instanceId>
    \\                    <imageId>ami-0e9dbfecae1768f17</imageId>
    \\                    <instanceState>
    \\                        <code>80</code>
    \\                        <name>stopped</name>
    \\                    </instanceState>
    \\                    <privateDnsName>ip-172-31-28-124.us-west-2.compute.internal</privateDnsName>
    \\                    <dnsName/>
    \\                    <reason>User initiated</reason>
    \\                    <amiLaunchIndex>0</amiLaunchIndex>
    \\                    <productCodes/>
    \\                    <instanceType>t3.small</instanceType>
    \\                    <launchTime>2021-07-16T18:49:06.000Z</launchTime>
    \\                    <placement>
    \\                        <availabilityZone>us-west-2b</availabilityZone>
    \\                        <groupName/>
    \\                        <tenancy>default</tenancy>
    \\                    </placement>
    \\                    <monitoring>
    \\                        <state>disabled</state>
    \\                    </monitoring>
    \\                    <subnetId>subnet-1f3f4278</subnetId>
    \\                    <vpcId>vpc-dc2402bb</vpcId>
    \\                    <privateIpAddress>172.31.28.124</privateIpAddress>
    \\                    <sourceDestCheck>true</sourceDestCheck>
    \\                    <groupSet>
    \\                        <item>
    \\                            <groupId>sg-08f08fa2f77bc26f4</groupId>
    \\                            <groupName>aws-cloud9-foo-394ec61bf1ca40188ec0701578b99e68-InstanceSecurityGroup-X63389OZJE9A</groupName>
    \\                        </item>
    \\                    </groupSet>
    \\                    <stateReason>
    \\                        <code>Client.InstanceInitiatedShutdown</code>
    \\                        <message>Client.InstanceInitiatedShutdown: Instance initiated shutdown</message>
    \\                    </stateReason>
    \\                    <architecture>x86_64</architecture>
    \\                    <rootDeviceType>ebs</rootDeviceType>
    \\                    <rootDeviceName>/dev/xvda</rootDeviceName>
    \\                    <blockDeviceMapping>
    \\                        <item>
    \\                            <deviceName>/dev/xvda</deviceName>
    \\                            <ebs>
    \\                                <volumeId>vol-00f20d00c3e7793db</volumeId>
    \\                                <status>attached</status>
    \\                                <attachTime>2021-07-14T16:56:39.000Z</attachTime>
    \\                                <deleteOnTermination>true</deleteOnTermination>
    \\                            </ebs>
    \\                        </item>
    \\                    </blockDeviceMapping>
    \\                    <virtualizationType>hvm</virtualizationType>
    \\                    <clientToken>aws-c-Insta-13W4473LX3CZH</clientToken>
    \\                    <tagSet>
    \\                        <item>
    \\                            <key>aws:cloud9:environment</key>
    \\                            <value>394ec61bf1ca40188ec0701578b99e68</value>
    \\                        </item>
    \\                        <item>
    \\                            <key>aws:cloudformation:logical-id</key>
    \\                            <value>Instance</value>
    \\                        </item>
    \\                        <item>
    \\                            <key>Name</key>
    \\                            <value>aws-cloud9-foo-394ec61bf1ca40188ec0701578b99e68</value>
    \\                        </item>
    \\                        <item>
    \\                            <key>aws:cloud9:owner</key>
    \\                            <value>550620852718:admin-nucman</value>
    \\                        </item>
    \\                        <item>
    \\                            <key>aws:cloudformation:stack-name</key>
    \\                            <value>aws-cloud9-foo-394ec61bf1ca40188ec0701578b99e68</value>
    \\                        </item>
    \\                        <item>
    \\                            <key>aws:cloudformation:stack-id</key>
    \\                            <value>arn:aws:cloudformation:us-west-2:550620852718:stack/aws-cloud9-foo-394ec61bf1ca40188ec0701578b99e68/6c4bec10-e4c4-11eb-8338-0266575e789f</value>
    \\                        </item>
    \\                    </tagSet>
    \\                    <hypervisor>xen</hypervisor>
    \\                    <networkInterfaceSet>
    \\                        <item>
    \\                            <networkInterfaceId>eni-0aea22ab476c131e8</networkInterfaceId>
    \\                            <subnetId>subnet-1f3f4278</subnetId>
    \\                            <vpcId>vpc-dc2402bb</vpcId>
    \\                            <description/>
    \\                            <ownerId>550620852718</ownerId>
    \\                            <status>in-use</status>
    \\                            <macAddress>02:e4:fe:61:88:ad</macAddress>
    \\                            <privateIpAddress>172.31.28.124</privateIpAddress>
    \\                            <privateDnsName>ip-172-31-28-124.us-west-2.compute.internal</privateDnsName>
    \\                            <sourceDestCheck>true</sourceDestCheck>
    \\                            <groupSet>
    \\                                <item>
    \\                                    <groupId>sg-08f08fa2f77bc26f4</groupId>
    \\                                    <groupName>aws-cloud9-foo-394ec61bf1ca40188ec0701578b99e68-InstanceSecurityGroup-X63389OZJE9A</groupName>
    \\                                </item>
    \\                            </groupSet>
    \\                            <attachment>
    \\                                <attachmentId>eni-attach-031a23d21bd9a9675</attachmentId>
    \\                                <deviceIndex>0</deviceIndex>
    \\                                <status>attached</status>
    \\                                <attachTime>2021-07-14T16:56:38.000Z</attachTime>
    \\                                <deleteOnTermination>true</deleteOnTermination>
    \\                                <networkCardIndex>0</networkCardIndex>
    \\                            </attachment>
    \\                            <privateIpAddressesSet>
    \\                                <item>
    \\                                    <privateIpAddress>172.31.28.124</privateIpAddress>
    \\                                    <privateDnsName>ip-172-31-28-124.us-west-2.compute.internal</privateDnsName>
    \\                                    <primary>true</primary>
    \\                                </item>
    \\                            </privateIpAddressesSet>
    \\                            <ipv6AddressesSet/>
    \\                            <interfaceType>interface</interfaceType>
    \\                        </item>
    \\                    </networkInterfaceSet>
    \\                    <ebsOptimized>false</ebsOptimized>
    \\                    <enaSupport>true</enaSupport>
    \\                    <cpuOptions>
    \\                        <coreCount>1</coreCount>
    \\                        <threadsPerCore>2</threadsPerCore>
    \\                    </cpuOptions>
    \\                    <capacityReservationSpecification>
    \\                        <capacityReservationPreference>open</capacityReservationPreference>
    \\                    </capacityReservationSpecification>
    \\                    <hibernationOptions>
    \\                        <configured>false</configured>
    \\                    </hibernationOptions>
    \\                    <enclaveOptions>
    \\                        <enabled>false</enabled>
    \\                    </enclaveOptions>
    \\                    <metadataOptions>
    \\                        <state>applied</state>
    \\                        <httpTokens>optional</httpTokens>
    \\                        <httpPutResponseHopLimit>1</httpPutResponseHopLimit>
    \\                        <httpEndpoint>enabled</httpEndpoint>
    \\                    </metadataOptions>
    \\                    <privateDnsNameOptions/>
    \\                </item>
    \\            </instancesSet>
    \\            <requesterId>658754138699</requesterId>
    \\        </item>
    \\        <item>
    \\            <reservationId>r-070573e68e0a31bab</reservationId>
    \\            <ownerId>550620852718</ownerId>
    \\            <groupSet/>
    \\            <instancesSet>
    \\                <item>
    \\                    <instanceId>i-097eaf8bea0e9a1be</instanceId>
    \\                    <imageId>ami-046b69c0f7b7428d5</imageId>
    \\                    <instanceState>
    \\                        <code>80</code>
    \\                        <name>stopped</name>
    \\                    </instanceState>
    \\                    <privateDnsName>ip-172-31-27-214.us-west-2.compute.internal</privateDnsName>
    \\                    <dnsName/>
    \\                    <reason>User initiated</reason>
    \\                    <amiLaunchIndex>0</amiLaunchIndex>
    \\                    <productCodes/>
    \\                    <instanceType>t3.small</instanceType>
    \\                    <launchTime>2021-07-16T18:54:31.000Z</launchTime>
    \\                    <placement>
    \\                        <availabilityZone>us-west-2b</availabilityZone>
    \\                        <groupName/>
    \\                        <tenancy>default</tenancy>
    \\                    </placement>
    \\                    <monitoring>
    \\                        <state>disabled</state>
    \\                    </monitoring>
    \\                    <subnetId>subnet-1f3f4278</subnetId>
    \\                    <vpcId>vpc-dc2402bb</vpcId>
    \\                    <privateIpAddress>172.31.27.214</privateIpAddress>
    \\                    <sourceDestCheck>true</sourceDestCheck>
    \\                    <groupSet>
    \\                        <item>
    \\                            <groupId>sg-05466b60f1a4ee056</groupId>
    \\                            <groupName>aws-cloud9-bar-1994a98a468e445ba4b5ad91dd93475b-InstanceSecurityGroup-7FL7ACV848S1</groupName>
    \\                        </item>
    \\                    </groupSet>
    \\                    <stateReason>
    \\                        <code>Client.InstanceInitiatedShutdown</code>
    \\                        <message>Client.InstanceInitiatedShutdown: Instance initiated shutdown</message>
    \\                    </stateReason>
    \\                    <architecture>x86_64</architecture>
    \\                    <rootDeviceType>ebs</rootDeviceType>
    \\                    <rootDeviceName>/dev/xvda</rootDeviceName>
    \\                    <blockDeviceMapping>
    \\                        <item>
    \\                            <deviceName>/dev/xvda</deviceName>
    \\                            <ebs>
    \\                                <volumeId>vol-0e99d9d6867118030</volumeId>
    \\                                <status>attached</status>
    \\                                <attachTime>2021-07-16T18:54:32.000Z</attachTime>
    \\                                <deleteOnTermination>true</deleteOnTermination>
    \\                            </ebs>
    \\                        </item>
    \\                    </blockDeviceMapping>
    \\                    <virtualizationType>hvm</virtualizationType>
    \\                    <clientToken>aws-c-Insta-1H5LO8S4BU1CS</clientToken>
    \\                    <tagSet>
    \\                        <item>
    \\                            <key>aws:cloudformation:stack-id</key>
    \\                            <value>arn:aws:cloudformation:us-west-2:550620852718:stack/aws-cloud9-bar-1994a98a468e445ba4b5ad91dd93475b/39a8dd00-e667-11eb-a967-02d5fabd30ef</value>
    \\                        </item>
    \\                        <item>
    \\                            <key>Name</key>
    \\                            <value>aws-cloud9-bar-1994a98a468e445ba4b5ad91dd93475b</value>
    \\                        </item>
    \\                        <item>
    \\                            <key>aws:cloud9:owner</key>
    \\                            <value>550620852718:admin-nucman</value>
    \\                        </item>
    \\                        <item>
    \\                            <key>aws:cloudformation:logical-id</key>
    \\                            <value>Instance</value>
    \\                        </item>
    \\                        <item>
    \\                            <key>aws:cloud9:environment</key>
    \\                            <value>1994a98a468e445ba4b5ad91dd93475b</value>
    \\                        </item>
    \\                        <item>
    \\                            <key>aws:cloudformation:stack-name</key>
    \\                            <value>aws-cloud9-bar-1994a98a468e445ba4b5ad91dd93475b</value>
    \\                        </item>
    \\                    </tagSet>
    \\                    <hypervisor>xen</hypervisor>
    \\                    <networkInterfaceSet>
    \\                        <item>
    \\                            <networkInterfaceId>eni-0dd0360c91184a496</networkInterfaceId>
    \\                            <subnetId>subnet-1f3f4278</subnetId>
    \\                            <vpcId>vpc-dc2402bb</vpcId>
    \\                            <description/>
    \\                            <ownerId>550620852718</ownerId>
    \\                            <status>in-use</status>
    \\                            <macAddress>02:84:8b:39:43:7f</macAddress>
    \\                            <privateIpAddress>172.31.27.214</privateIpAddress>
    \\                            <privateDnsName>ip-172-31-27-214.us-west-2.compute.internal</privateDnsName>
    \\                            <sourceDestCheck>true</sourceDestCheck>
    \\                            <groupSet>
    \\                                <item>
    \\                                    <groupId>sg-05466b60f1a4ee056</groupId>
    \\                                    <groupName>aws-cloud9-bar-1994a98a468e445ba4b5ad91dd93475b-InstanceSecurityGroup-7FL7ACV848S1</groupName>
    \\                                </item>
    \\                            </groupSet>
    \\                            <attachment>
    \\                                <attachmentId>eni-attach-00d320672fdf08bc2</attachmentId>
    \\                                <deviceIndex>0</deviceIndex>
    \\                                <status>attached</status>
    \\                                <attachTime>2021-07-16T18:54:31.000Z</attachTime>
    \\                                <deleteOnTermination>true</deleteOnTermination>
    \\                                <networkCardIndex>0</networkCardIndex>
    \\                            </attachment>
    \\                            <privateIpAddressesSet>
    \\                                <item>
    \\                                    <privateIpAddress>172.31.27.214</privateIpAddress>
    \\                                    <privateDnsName>ip-172-31-27-214.us-west-2.compute.internal</privateDnsName>
    \\                                    <primary>true</primary>
    \\                                </item>
    \\                            </privateIpAddressesSet>
    \\                            <ipv6AddressesSet/>
    \\                            <interfaceType>interface</interfaceType>
    \\                        </item>
    \\                    </networkInterfaceSet>
    \\                    <ebsOptimized>false</ebsOptimized>
    \\                    <enaSupport>true</enaSupport>
    \\                    <cpuOptions>
    \\                        <coreCount>1</coreCount>
    \\                        <threadsPerCore>2</threadsPerCore>
    \\                    </cpuOptions>
    \\                    <capacityReservationSpecification>
    \\                        <capacityReservationPreference>open</capacityReservationPreference>
    \\                    </capacityReservationSpecification>
    \\                    <hibernationOptions>
    \\                        <configured>false</configured>
    \\                    </hibernationOptions>
    \\                    <enclaveOptions>
    \\                        <enabled>false</enabled>
    \\                    </enclaveOptions>
    \\                    <metadataOptions>
    \\                        <state>applied</state>
    \\                        <httpTokens>optional</httpTokens>
    \\                        <httpPutResponseHopLimit>1</httpPutResponseHopLimit>
    \\                        <httpEndpoint>enabled</httpEndpoint>
    \\                    </metadataOptions>
    \\                    <privateDnsNameOptions/>
    \\                </item>
    \\            </instancesSet>
    \\            <requesterId>658754138699</requesterId>
    \\        </item>
    \\        <item>
    \\            <reservationId>r-099bdc75a5ab8419b</reservationId>
    \\            <ownerId>550620852718</ownerId>
    \\            <groupSet/>
    \\            <instancesSet>
    \\                <item>
    \\                    <instanceId>i-08a2569c63ff8e87e</instanceId>
    \\                    <imageId>ami-067d3e2d50855f7d6</imageId>
    \\                    <instanceState>
    \\                        <code>16</code>
    \\                        <name>running</name>
    \\                    </instanceState>
    \\                    <privateDnsName>ip-172-31-48-70.us-west-2.compute.internal</privateDnsName>
    \\                    <dnsName>ec2-34-222-191-26.us-west-2.compute.amazonaws.com</dnsName>
    \\                    <reason/>
    \\                    <keyName>_gpg</keyName>
    \\                    <amiLaunchIndex>0</amiLaunchIndex>
    \\                    <productCodes/>
    \\                    <instanceType>t3.xlarge</instanceType>
    \\                    <launchTime>2021-06-21T17:43:54.000Z</launchTime>
    \\                    <placement>
    \\                        <availabilityZone>us-west-2d</availabilityZone>
    \\                        <groupName/>
    \\                        <tenancy>default</tenancy>
    \\                    </placement>
    \\                    <platform>windows</platform>
    \\                    <monitoring>
    \\                        <state>disabled</state>
    \\                    </monitoring>
    \\                    <subnetId>subnet-7ba0e853</subnetId>
    \\                    <vpcId>vpc-dc2402bb</vpcId>
    \\                    <privateIpAddress>172.31.48.70</privateIpAddress>
    \\                    <ipAddress>34.222.191.26</ipAddress>
    \\                    <sourceDestCheck>true</sourceDestCheck>
    \\                    <groupSet>
    \\                        <item>
    \\                            <groupId>sg-00ffec335f6c35ce3</groupId>
    \\                            <groupName>rdp</groupName>
    \\                        </item>
    \\                        <item>
    \\                            <groupId>sg-0aab58c6b2bde2105</groupId>
    \\                            <groupName>outbound</groupName>
    \\                        </item>
    \\                    </groupSet>
    \\                    <architecture>x86_64</architecture>
    \\                    <rootDeviceType>ebs</rootDeviceType>
    \\                    <rootDeviceName>/dev/sda1</rootDeviceName>
    \\                    <blockDeviceMapping>
    \\                        <item>
    \\                            <deviceName>/dev/sda1</deviceName>
    \\                            <ebs>
    \\                                <volumeId>vol-0b2093ed03d0fba04</volumeId>
    \\                                <status>attached</status>
    \\                                <attachTime>2021-06-21T17:43:55.000Z</attachTime>
    \\                                <deleteOnTermination>true</deleteOnTermination>
    \\                            </ebs>
    \\                        </item>
    \\                    </blockDeviceMapping>
    \\                    <virtualizationType>hvm</virtualizationType>
    \\                    <clientToken/>
    \\                    <tagSet>
    \\                        <item>
    \\                            <key>Name</key>
    \\                            <value>VS/Windows Dev</value>
    \\                        </item>
    \\                        <item>
    \\                            <key>lerchdev</key>
    \\                            <value>vs</value>
    \\                        </item>
    \\                    </tagSet>
    \\                    <hypervisor>xen</hypervisor>
    \\                    <networkInterfaceSet>
    \\                        <item>
    \\                            <networkInterfaceId>eni-0e46f76afdab4ea78</networkInterfaceId>
    \\                            <subnetId>subnet-7ba0e853</subnetId>
    \\                            <vpcId>vpc-dc2402bb</vpcId>
    \\                            <description/>
    \\                            <ownerId>550620852718</ownerId>
    \\                            <status>in-use</status>
    \\                            <macAddress>0e:5c:d9:6d:fa:01</macAddress>
    \\                            <privateIpAddress>172.31.48.70</privateIpAddress>
    \\                            <privateDnsName>ip-172-31-48-70.us-west-2.compute.internal</privateDnsName>
    \\                            <sourceDestCheck>true</sourceDestCheck>
    \\                            <groupSet>
    \\                                <item>
    \\                                    <groupId>sg-00ffec335f6c35ce3</groupId>
    \\                                    <groupName>rdp</groupName>
    \\                                </item>
    \\                                <item>
    \\                                    <groupId>sg-0aab58c6b2bde2105</groupId>
    \\                                    <groupName>outbound</groupName>
    \\                                </item>
    \\                            </groupSet>
    \\                            <attachment>
    \\                                <attachmentId>eni-attach-0a793e5c67bf91ad3</attachmentId>
    \\                                <deviceIndex>0</deviceIndex>
    \\                                <status>attached</status>
    \\                                <attachTime>2021-06-21T17:43:54.000Z</attachTime>
    \\                                <deleteOnTermination>true</deleteOnTermination>
    \\                                <networkCardIndex>0</networkCardIndex>
    \\                            </attachment>
    \\                            <association>
    \\                                <publicIp>34.222.191.26</publicIp>
    \\                                <publicDnsName>ec2-34-222-191-26.us-west-2.compute.amazonaws.com</publicDnsName>
    \\                                <ipOwnerId>amazon</ipOwnerId>
    \\                            </association>
    \\                            <privateIpAddressesSet>
    \\                                <item>
    \\                                    <privateIpAddress>172.31.48.70</privateIpAddress>
    \\                                    <privateDnsName>ip-172-31-48-70.us-west-2.compute.internal</privateDnsName>
    \\                                    <primary>true</primary>
    \\                                    <association>
    \\                                    <publicIp>34.222.191.26</publicIp>
    \\                                    <publicDnsName>ec2-34-222-191-26.us-west-2.compute.amazonaws.com</publicDnsName>
    \\                                    <ipOwnerId>amazon</ipOwnerId>
    \\                                    </association>
    \\                                </item>
    \\                            </privateIpAddressesSet>
    \\                            <ipv6AddressesSet/>
    \\                            <interfaceType>interface</interfaceType>
    \\                        </item>
    \\                    </networkInterfaceSet>
    \\                    <iamInstanceProfile>
    \\                        <arn>arn:aws:iam::550620852718:instance-profile/ec2-dev</arn>
    \\                        <id>AIPAYAM4POHXCFNKZ7HU2</id>
    \\                    </iamInstanceProfile>
    \\                    <ebsOptimized>true</ebsOptimized>
    \\                    <enaSupport>true</enaSupport>
    \\                    <cpuOptions>
    \\                        <coreCount>2</coreCount>
    \\                        <threadsPerCore>2</threadsPerCore>
    \\                    </cpuOptions>
    \\                    <capacityReservationSpecification>
    \\                        <capacityReservationPreference>open</capacityReservationPreference>
    \\                    </capacityReservationSpecification>
    \\                    <hibernationOptions>
    \\                        <configured>true</configured>
    \\                    </hibernationOptions>
    \\                    <enclaveOptions>
    \\                        <enabled>false</enabled>
    \\                    </enclaveOptions>
    \\                    <metadataOptions>
    \\                        <state>applied</state>
    \\                        <httpTokens>optional</httpTokens>
    \\                        <httpPutResponseHopLimit>1</httpPutResponseHopLimit>
    \\                        <httpEndpoint>enabled</httpEndpoint>
    \\                    </metadataOptions>
    \\                    <privateDnsNameOptions/>
    \\                </item>
    \\            </instancesSet>
    \\        </item>
    \\    </reservationSet>
    \\</DescribeInstancesResponse>
;
